---
abstract: 'Use libraries from a t/lib directory'
author:
  - 'Graham Knop <haarg@haarg.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Lib
no_index:
  directory:
    - t
    - inc
requires:
  Cwd: 0
  File::Spec: 0
  strict: 0
version: 0.001
